# starship config
format = """
 $username\
 $hostname\
 $directory\
 $git_branch\
 $git_commit\
 $git_state\
 $git_status\
 $python\
 $memory_usage\
 $env_var\
 $cmd_duration\
 $custom\
 $line_break\
 $jobs\
 $time\
 $character\
"""

[directory]
truncate_to_repo=false
truncation_length=20
style="blue"

[git_branch]
style="dimmed blue"

[git_commit]
style="FFC0CB"
# modified.style="FFC0CB"

[git_state]
style="FFC0CB"
# modified.style="FFC0CB"

[git_status]
style="FFC0CB"
# modified.style="FFC0CB"

[cmd_duration]
# prefix=""

[character]
# style_success="purple"

